name: Docker Compose Up

on:
  push:
    branches:
      - main

jobs:
  docker-compose-up:
    container: docker:20.10.8
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Docker Compose
      run: |
        wget -O /usr/local/bin/docker-compose "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)"
        chmod +x /usr/local/bin/docker-compose

    - name: Show Docker Compose Version
      run: docker-compose --version

    - name: Docker Compose Up
      run: docker-compose -f docker-compose.yml -f docker-compose.override.yml up -d
