name: Docker Compose Up

on:
  push:
    branches:
      - main

jobs:
  docker-compose-up:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: docker/setup-docker@v2
      with:
        docker-compose-version:  1.29.2 # Change to the appropriate version if needed

    - name: Show Docker Compose Version
      run: docker-compose --version

    - name: Build and Run Microservices with Docker Compose
      run: docker-compose -f docker-compose.yml -f docker-compose.override.yml up -d
