name: Docker Compose Up

on:
  push:
    branches:
      - main

jobs:
  docker-compose-up:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Show Docker Version
      run: docker --version

    - name: Install Docker Compose
      run: |
        # Add the steps to install Docker Compose on Windows.
        # Use curl or any other appropriate method for Windows.
        # Note that the paths might be different in Windows.

    - name: Show Docker Compose Version
      run: docker-compose --version

    - name: Docker Compose Up
      run: docker-compose -f docker-compose.yml -f docker-compose.override.yml up -d
