name: Docker Compose Up

on:
  push:
    branches:
      - main

jobs:
  docker-compose-up:
    container: docker:20.10.8
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Compose
      run: docker-compose --version

    - name: Docker Compose Up
      run: docker-compose -f docker-compose.yml -f docker-compose.override.yml up -d
