name: Build and Test Microservices

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build and Test Microservices
      run: |
        for folder in src/*; do
          if [ -d "$folder" ]; then
            cd "$folder"
            docker build -t your-docker-registry/your-image-name .
            docker run your-docker-registry/your-image-name dotnet test --no-restore
            cd -
          fi
        done
