name: Build and Test ECommerce.Api.Customers

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build ECommerce.Api.Customers
      run: dotnet build ECommerce.Api.Customers

    - name: Test ECommerce.Api.Customers
      run: dotnet test ECommerce.Api.Customers
